### ISSUE TITLE
On redirect, requests are not sending orignal headers to subsequent locations

### ISSUE THREAD

**Issue by kcajmagic** [xmidt-org/xmidt-agent#188]
# Description
When starting the `xmidt-agent`, the auth header from themis is not being added to requests after receiving a redirect from petasos.

# Reproduce 
1. Stand up xmidt cluster with themis, and set talaria to not fail open.
2. tail logs of talaria

Here is an example of a log line notice no auth is present.
```
{"level":"error","ts":"2024-07-10T15:59:44Z","msg":"no authorization header","requestHeaders":{"Accept-Encoding":["gzip"],"Connection":["Upgrade"],"Referer":["https://petasos.example.com:8080/api/v2/device"],"Sec-Websocket-Key":["AOlEYfKBp3Fza5mflg6ePg=="],"Sec-Websocket-Version":["13"],"Upgrade":["websocket"],"User-Agent":["Go-http-client/1.1"],"X-Webpa-Convey":["eyJib290LXRpbWUiOiIxOTcwLTAxLTAxIDAwOjAwOjAwICswMDAwIFVUQyIsImJvb3QtdGltZS1yZXRyeS13YWl0IjoiMSIsImZ3LW5hbWUiOiJ2MC4wLjEiLCJody1sYXN0LXJlYm9vdC1yZWFzb24iOiJzbGVlcHkiLCJody1tYW51ZmFjdHVyZXIiOiJiYXJNYW51ZmFjdHVyZXIiLCJody1tb2RlbCI6ImZvb01vZGVsIiwiaHctc2VyaWFsLW51bWJlciI6IjE4MDBkZWFkYmVlZiIsImludGVyZmFjZXMtYXZhaWxhYmxlIjoiZXRoMCIsIndlYnBhLWludGVyZmFjZS11c2VkIjoiZXJvdXRlcjAiLCJ3ZWJwYS1wcm90b2NvbCI6InByb3RvY29sIn0="],"X-Webpa-Device-Name":["mac:4ca161000108"]},"requestURL":"/api/v2/device","method":"GET","requestURI":"/api/v2/device","remoteAddr":"","ts":"2024-07-10T15:59:44Z","auth":""}
```

# Expected behavior
The device should be connect to the cluster with some trust level.

**Comment by denopink** [comment]
Hi @kcajmagic !

Thanks for the ticket. I took a quick look and setup the following local cluster:
- themis
- petasos
- talaria (with openfail disabled)

## TL;DR

I wasn't able to reproduce your issue.

I'm seeing `xmidt-agent -> petasos -> talaria` behaving as expected, i.e.: talaria is still receiving the `Authorization` header.

Here's the headers that my local talaria is receiving:
```
[
    "Authorization": [
        "Bearer SOME-THEMIS-JWT"
    ],
    "Referer": [
        "http://localhost:6400/api/v2/device"
    ],
    "Sec-Websocket-Key": [
        "i5aIEZN5QLU6Enq+puDXaA=="
    ],
    "Sec-Websocket-Version": [
        "13"
    ],
    "User-Agent": [
        "Go-http-client/1.1"
    ],
    "Connection": [
        "Upgrade"
    ],
    "Upgrade": [
        "websocket"
    ],
    "X-Webpa-Convey": [
        "SOME-CONVEY-DATA"
    ],
    "X-Webpa-Device-Name": [
        "mac:1800deadbeef"
    ],
    "Accept-Encoding": [
        "gzip"
    ],
]
```

I think your issue is likely a xmidt-agent configuration issue, can you share your config?

If your using the default config, here's what your config suppose to look like when you want to your xmidt-agent to fetch a themis token (section `xmidt_credentials`):

```yaml
websocket:
  url_path: api/v2/device
  # petasos server
  back_up_url: http://localhost:6400
xmidt_credentials:
  # themis server
  url: https://localhost:8080/issue
  file_name: themis-creds.jwt
  file_permissions: 0777
  http_client:
    tls:
      insecure_skip_verify: true
      certificates: 
      # UPDATE certificate_file & key_file with actual file paths
        - certificate_file: crt.pem
          key_file:         key.pem
      min_version: 771 # 0x0303, the TLS 1.2 version uint16
identity:
  device_id: mac:1800deadbeef
  serial_number: 1800deadbeef
  hardware_model: fooModel
  hardware_manufacturer: barManufacturer
  firmware_version: v0.0.1
  partner_id: foobar
operational_state:
  last_reboot_reason: sleepy
  boot_time: "2024-02-28T01:04:27Z"
mock_tr_181:
  enabled: true
  file_path: mock_tr181.json
```

Hope this helps and let me know if I misunderstood anything or you need additional information!
