### ISSUE TITLE
Support cherry picking configuration from external files.

### ISSUE THREAD

**Issue by schmidtw** [xmidt-org/xmidt-agent#91]
To help reduce the need for shell scripts at startup it would be ideal if the agent can be configured to cherry pick configuration values from other files that aren't part of the core files.

For example, from a file named: `/var/run/example.txt` we might want to pull a few values.

```
Device.X_RDK_WebPA_Server.URL=https://fabric.xmidt.example.com
Device.X_RDK_WebPA_DNSText.URL=fabric.xmidt.example.com
Device.X_RDK_WebPA_TokenServer.URL=https://issuer.xmidt.example.com/issue
```

Into the normal configuration like this:

```yaml
websocket:
  url_path: /api/v2/device
xmidt_credentials:
  url: ${TOKEN_URL}
externals:
  -
    file: /var/run/example.txt
    as: properties
    origin: example.txt
    remap:
      - from: Device.X_RDK_WebPA_Server.URL
        to: XMIDT_URL
      - from: Device.X_RDK_WebPA_DNSText.URL
        to: DNS_URL
      - from: Device.X_RDK_WebPA_TokenServer.URL
        to: TOKEN_URL
```

The result is that the `xmidt_credentials.url` = `https://issuer.xmidt.example.com/issue`
